"""initial_production_schema

Revision ID: f48420fc1dd0
Revises: 
Create Date: 2026-09-19 10:17:18.466750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f48420fc1dd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_challenge_categories_id'), 'challenge_categories', ['id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('total_population', sa.Integer(), nullable=True),
    sa.Column('rural_population_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)
    op.create_table('government_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_departments_id'), 'government_departments', ['id'], unique=False)
    op.create_table('impact_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_name')
    )
    op.create_index(op.f('ix_impact_metrics_id'), 'impact_metrics', ['id'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_id'), 'revoked_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'UNIVERSITY', 'STUDENT', 'FACULTY_MENTOR', 'INDUSTRY', 'GOVERNMENT_ADMIN', name='userrole'), nullable=False),
    sa.Column('admin_tier', sa.String(length=50), nullable=True),
    sa.Column('jurisdiction_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_state', sa.Text(), nullable=True),
    sa.Column('new_state', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_role'), 'audit_logs', ['actor_role'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('citizens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('district_name', sa.String(length=100), nullable=True),
    sa.Column('block_name', sa.String(length=100), nullable=True),
    sa.Column('village_or_city', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_citizens_id'), 'citizens', ['id'], unique=False)
    op.create_table('industry_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry_domain', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('csr_focus_areas', sa.Text(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('available_support', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_industry_partners_company_name'), 'industry_partners', ['company_name'], unique=False)
    op.create_index(op.f('ix_industry_partners_id'), 'industry_partners', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('organization_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=100), nullable=False),
    sa.Column('reg_number', sa.String(length=100), nullable=True),
    sa.Column('official_email', sa.String(length=255), nullable=False),
    sa.Column('official_domain', sa.String(length=255), nullable=True),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('submitted_documents', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_organization_profiles_id'), 'organization_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_organization_profiles_legal_name'), 'organization_profiles', ['legal_name'], unique=False)
    op.create_index(op.f('ix_organization_profiles_org_type'), 'organization_profiles', ['org_type'], unique=False)
    op.create_index(op.f('ix_organization_profiles_reg_number'), 'organization_profiles', ['reg_number'], unique=False)
    op.create_index(op.f('ix_organization_profiles_verification_status'), 'organization_profiles', ['verification_status'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('has_incubation_center', sa.Boolean(), nullable=True),
    sa.Column('has_innovation_center', sa.Boolean(), nullable=True),
    sa.Column('facilities_description', sa.Text(), nullable=True),
    sa.Column('nirf_ranking', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_index(op.f('ix_universities_institution_name'), 'universities', ['institution_name'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='challengepriority'), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'AI_ANALYSIS', 'UNDER_REVIEW', 'NEEDS_MORE_INFO', 'DUPLICATE', 'VALIDATED', 'UNIVERSITY_ASSIGNED', 'TEAM_FORMED', 'SOLUTION_PROPOSED', 'APPROVED', 'PROTOTYPE', 'FIELD_TESTING', 'DEPLOYMENT', 'IN_PROGRESS', 'FIELD_VERIFICATION', 'RESOLVED', 'CLOSED', 'REJECTED', name='challengestatus'), nullable=True),
    sa.Column('current_tier', sa.String(length=50), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('escalated_by', sa.String(length=255), nullable=True),
    sa.Column('escalation_remarks', sa.Text(), nullable=True),
    sa.Column('citizen_id', sa.Integer(), nullable=True),
    sa.Column('assigned_university_id', sa.Integer(), nullable=True),
    sa.Column('affected_population', sa.Integer(), nullable=True),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('moderated_by', sa.String(length=255), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_category'), 'challenges', ['category'], unique=False)
    op.create_index(op.f('ix_challenges_current_tier'), 'challenges', ['current_tier'], unique=False)
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_index(op.f('ix_challenges_priority'), 'challenges', ['priority'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.create_index(op.f('ix_challenges_title'), 'challenges', ['title'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('head_of_department', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('university_expertise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('focus_area', sa.String(length=255), nullable=True),
    sa.Column('score_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_expertise_domain'), 'university_expertise', ['domain'], unique=False)
    op.create_index(op.f('ix_university_expertise_id'), 'university_expertise', ['id'], unique=False)
    op.create_table('ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('classified_domain', sa.String(length=100), nullable=False),
    sa.Column('detected_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='challengepriority'), nullable=False),
    sa.Column('extracted_keywords', sa.Text(), nullable=True),
    sa.Column('required_expertise', sa.Text(), nullable=True),
    sa.Column('recommended_solution', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id')
    )
    op.create_index(op.f('ix_ai_analysis_id'), 'ai_analysis', ['id'], unique=False)
    op.create_table('challenge_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('block_name', sa.String(length=100), nullable=True),
    sa.Column('village_or_city', sa.String(length=100), nullable=True),
    sa.Column('location_address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id')
    )
    op.create_index(op.f('ix_challenge_locations_district_name'), 'challenge_locations', ['district_name'], unique=False)
    op.create_index(op.f('ix_challenge_locations_id'), 'challenge_locations', ['id'], unique=False)
    op.create_table('challenge_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_media_id'), 'challenge_media', ['id'], unique=False)
    op.create_table('challenge_similarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('similar_challenge_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('matched_keywords', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['similar_challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_similarity_id'), 'challenge_similarity', ['id'], unique=False)
    op.create_table('citizen_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_issue_resolved', sa.Boolean(), nullable=True),
    sa.Column('satisfaction_score', sa.Float(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('evidence_photo_url', sa.String(length=500), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_feedback_challenge_id'), 'citizen_feedback', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_citizen_feedback_citizen_id'), 'citizen_feedback', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_citizen_feedback_id'), 'citizen_feedback', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('expertise', sa.String(length=255), nullable=True),
    sa.Column('research_interests', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_faculty_id'), 'faculty', ['id'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_id'), 'status_history', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('year_of_study', sa.Integer(), nullable=True),
    sa.Column('skills', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('university_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('match_percentage', sa.Float(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('matching_factors', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_matches_id'), 'university_matches', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('faculty_mentor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('timeline_months', sa.Integer(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['faculty_mentor_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('industry_collaborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('industry_id', sa.Integer(), nullable=False),
    sa.Column('offer_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['industry_id'], ['industry_partners.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_collaborations_id'), 'industry_collaborations', ['id'], unique=False)
    op.create_table('project_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_documents_id'), 'project_documents', ['id'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role_in_team', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_table('project_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('weight_pct', sa.Float(), nullable=True),
    sa.Column('deliverable_files', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'COMPLETED', name='milestonestatus'), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by_faculty', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_milestones_id'), 'project_milestones', ['id'], unique=False)
    op.create_table('project_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('assigned_to_student_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('submission_notes', sa.Text(), nullable=True),
    sa.Column('submission_attachment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_tasks_id'), 'project_tasks', ['id'], unique=False)
    op.create_table('solution_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('proposed_solution', sa.Text(), nullable=False),
    sa.Column('technical_approach', sa.Text(), nullable=False),
    sa.Column('required_resources', sa.Text(), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('timeline_weeks', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('is_approved_by_gov', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_proposals_id'), 'solution_proposals', ['id'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('verification_type', sa.String(length=100), nullable=False),
    sa.Column('inspector_name', sa.String(length=255), nullable=False),
    sa.Column('inspector_role', sa.String(length=100), nullable=False),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('evidence_urls', sa.Text(), nullable=True),
    sa.Column('geotagged_lat', sa.Float(), nullable=True),
    sa.Column('geotagged_lng', sa.Float(), nullable=True),
    sa.Column('inspection_notes', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['project_milestones.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_id'), 'verification_records', ['id'], unique=False)
    op.create_index(op.f('ix_verification_records_project_id'), 'verification_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_verification_records_verification_status'), 'verification_records', ['verification_status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_records_verification_status'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_project_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_id'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_solution_proposals_id'), table_name='solution_proposals')
    op.drop_table('solution_proposals')
    op.drop_index(op.f('ix_project_tasks_id'), table_name='project_tasks')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_project_milestones_id'), table_name='project_milestones')
    op.drop_table('project_milestones')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_project_documents_id'), table_name='project_documents')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_industry_collaborations_id'), table_name='industry_collaborations')
    op.drop_table('industry_collaborations')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_university_matches_id'), table_name='university_matches')
    op.drop_table('university_matches')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_status_history_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_faculty_id'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_citizen_feedback_id'), table_name='citizen_feedback')
    op.drop_index(op.f('ix_citizen_feedback_citizen_id'), table_name='citizen_feedback')
    op.drop_index(op.f('ix_citizen_feedback_challenge_id'), table_name='citizen_feedback')
    op.drop_table('citizen_feedback')
    op.drop_index(op.f('ix_challenge_similarity_id'), table_name='challenge_similarity')
    op.drop_table('challenge_similarity')
    op.drop_index(op.f('ix_challenge_media_id'), table_name='challenge_media')
    op.drop_table('challenge_media')
    op.drop_index(op.f('ix_challenge_locations_id'), table_name='challenge_locations')
    op.drop_index(op.f('ix_challenge_locations_district_name'), table_name='challenge_locations')
    op.drop_table('challenge_locations')
    op.drop_index(op.f('ix_ai_analysis_id'), table_name='ai_analysis')
    op.drop_table('ai_analysis')
    op.drop_index(op.f('ix_university_expertise_id'), table_name='university_expertise')
    op.drop_index(op.f('ix_university_expertise_domain'), table_name='university_expertise')
    op.drop_table('university_expertise')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_challenges_title'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_priority'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_current_tier'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_category'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_universities_institution_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_organization_profiles_verification_status'), table_name='organization_profiles')
    op.drop_index(op.f('ix_organization_profiles_reg_number'), table_name='organization_profiles')
    op.drop_index(op.f('ix_organization_profiles_org_type'), table_name='organization_profiles')
    op.drop_index(op.f('ix_organization_profiles_legal_name'), table_name='organization_profiles')
    op.drop_index(op.f('ix_organization_profiles_id'), table_name='organization_profiles')
    op.drop_table('organization_profiles')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_industry_partners_id'), table_name='industry_partners')
    op.drop_index(op.f('ix_industry_partners_company_name'), table_name='industry_partners')
    op.drop_table('industry_partners')
    op.drop_index(op.f('ix_citizens_id'), table_name='citizens')
    op.drop_table('citizens')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_role'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_id'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_impact_metrics_id'), table_name='impact_metrics')
    op.drop_table('impact_metrics')
    op.drop_index(op.f('ix_government_departments_id'), table_name='government_departments')
    op.drop_table('government_departments')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_challenge_categories_id'), table_name='challenge_categories')
    op.drop_table('challenge_categories')
    # ### end Alembic commands ###

    # Drop enum types on PostgreSQL safely
    bind = op.get_bind()
    if bind.dialect.name == 'postgresql':
        for enum_name in ['milestonestatus', 'challengestatus', 'challengepriority', 'userrole']:
            op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name} CASCADE"))

